// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20210701210450_ReName")]
    partial class ReName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Rating");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("UserReview")
                        .IsRequired();

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            City = "Rorcek",
                            Country = "Sweden",
                            Rating = 7,
                            UserName = "Malinda",
                            UserReview = "Wonderful and sublime. Fantastic atmostphere and amazing people."
                        },
                        new
                        {
                            ReviewId = 2,
                            City = "England",
                            Country = "America",
                            Rating = 2,
                            UserName = "Charlie",
                            UserReview = "Terrible, this is not the england I was promised."
                        },
                        new
                        {
                            ReviewId = 3,
                            City = "Topnick",
                            Country = "Ireland",
                            Rating = 6,
                            UserName = "Derik",
                            UserReview = "Cold and rainy, but fantasic food and drinks!"
                        },
                        new
                        {
                            ReviewId = 4,
                            City = "Tokyo",
                            Country = "Japan",
                            Rating = 9,
                            UserName = "Amy",
                            UserReview = "An eastern version of New York City!"
                        },
                        new
                        {
                            ReviewId = 5,
                            City = "YorkTown",
                            Country = "England",
                            Rating = 3,
                            UserName = "Bob",
                            UserReview = "Don't know what I was expexting, but it wasn't this."
                        },
                        new
                        {
                            ReviewId = 6,
                            City = "Tokyo",
                            Country = "Japan",
                            Rating = 7,
                            UserName = "Bob",
                            UserReview = "Nice place. Perfect for the busy city life that I enjoy."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
